-- MySQL Script generated by MySQL Workbench
-- Sun May 12 20:25:26 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_buffet
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_buffet` ;

-- -----------------------------------------------------
-- Schema db_buffet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_buffet` DEFAULT CHARACTER SET utf8mb4 ;
USE `db_buffet` ;

-- -----------------------------------------------------
-- Table `db_buffet`.`tb_buffet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_buffet`.`tb_buffet` ;

CREATE TABLE IF NOT EXISTS `db_buffet`.`tb_buffet` (
  `cd_buffet` INT NOT NULL AUTO_INCREMENT,
  `nm_buffet` VARCHAR(50) NOT NULL,
  `nm_usuario` VARCHAR(30) NOT NULL,
  `cd_senha` VARCHAR(100) NOT NULL,
  `st_buffet` CHAR(1) NOT NULL,
  PRIMARY KEY (`cd_buffet`),
  UNIQUE INDEX `nm_usuario_UNIQUE` (`nm_usuario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_buffet`.`tb_categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_buffet`.`tb_categoria` ;

CREATE TABLE IF NOT EXISTS `db_buffet`.`tb_categoria` (
  `cd_categoria` INT NOT NULL AUTO_INCREMENT,
  `nm_categoria` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`cd_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_buffet`.`tb_compra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_buffet`.`tb_compra` ;

CREATE TABLE IF NOT EXISTS `db_buffet`.`tb_compra` (
  `cd_compra` INT NOT NULL AUTO_INCREMENT,
  `dt_compra` DATETIME NOT NULL DEFAULT current_timestamp,
  `qt_compra` INT(10) NOT NULL,
  `vl_compra` DECIMAL(6,2) NOT NULL,
  `id_produto` INT NOT NULL,
  `id_fornecedor` INT NOT NULL,
  PRIMARY KEY (`cd_compra`),
  INDEX `fk_tb_compra_tb_produto1_idx` (`id_produto` ASC) VISIBLE,
  INDEX `fk_tb_compra_tb_fornecedor1_idx` (`id_fornecedor` ASC) VISIBLE,
  CONSTRAINT `fk_tb_compra_tb_produto1`
    FOREIGN KEY (`id_produto`)
    REFERENCES `db_buffet`.`tb_produto` (`cd_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_compra_tb_fornecedor1`
    FOREIGN KEY (`id_fornecedor`)
    REFERENCES `db_buffet`.`tb_fornecedor` (`cd_fornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_buffet`.`tb_configuracao_buffet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_buffet`.`tb_configuracao_buffet` ;

CREATE TABLE IF NOT EXISTS `db_buffet`.`tb_configuracao_buffet` (
  `cd_configuracao_buffet` INT NOT NULL AUTO_INCREMENT,
  `tm_intervalo_pedido` SMALLINT NOT NULL,
  `qt_maxima_cada_produto` SMALLINT NOT NULL,
  `qt_maxima_produto_pedido` SMALLINT NOT NULL,
  `qt_maxima_convidados` INT NOT NULL,
  `id_buffet` INT NOT NULL,
  PRIMARY KEY (`cd_configuracao_buffet`),
  INDEX `fk_tb_configuracao_buffet_tb_buffet1_idx` (`id_buffet` ASC) VISIBLE,
  CONSTRAINT `fk_tb_configuracao_buffet_tb_buffet1`
    FOREIGN KEY (`id_buffet`)
    REFERENCES `db_buffet`.`tb_buffet` (`cd_buffet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_buffet`.`tb_endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_buffet`.`tb_endereco` ;

CREATE TABLE IF NOT EXISTS `db_buffet`.`tb_endereco` (
  `cd_endereco` INT NOT NULL AUTO_INCREMENT,
  `nm_complemento` VARCHAR(100) NULL,
  `nr_numero` TINYINT NOT NULL,
  `nm_rua` VARCHAR(150) NOT NULL,
  `nm_bairro` VARCHAR(50) NOT NULL,
  `nm_cidade` VARCHAR(50) NOT NULL,
  `cd_uf` CHAR(2) NOT NULL,
  `cd_cep` VARCHAR(10) NOT NULL,
  `id_buffet` INT NOT NULL,
  PRIMARY KEY (`cd_endereco`),
  INDEX `fk_tb_endereco_tb_buffet1_idx` (`id_buffet` ASC) VISIBLE,
  CONSTRAINT `fk_tb_endereco_tb_buffet1`
    FOREIGN KEY (`id_buffet`)
    REFERENCES `db_buffet`.`tb_buffet` (`cd_buffet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_buffet`.`tb_envio_email`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_buffet`.`tb_envio_email` ;

CREATE TABLE IF NOT EXISTS `db_buffet`.`tb_envio_email` (
  `cd_envio_email` INT NOT NULL AUTO_INCREMENT,
  `dt_envio` DATETIME NOT NULL DEFAULT current_timestamp,
  `nm_titulo` VARCHAR(100) NOT NULL,
  `nm_conteudo` TEXT NOT NULL,
  `id_fornecedor` INT NOT NULL,
  PRIMARY KEY (`cd_envio_email`),
  INDEX `fk_tb_envio_email_tb_fornecedor1_idx` (`id_fornecedor` ASC) VISIBLE,
  CONSTRAINT `fk_tb_envio_email_tb_fornecedor1`
    FOREIGN KEY (`id_fornecedor`)
    REFERENCES `db_buffet`.`tb_fornecedor` (`cd_fornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_buffet`.`tb_festa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_buffet`.`tb_festa` ;

CREATE TABLE IF NOT EXISTS `db_buffet`.`tb_festa` (
  `cd_festa` INT NOT NULL AUTO_INCREMENT,
  `dt_inicio` DATETIME NOT NULL,
  `dt_fim` DATETIME NOT NULL,
  `qt_convidados` INT NOT NULL,
  `nm_aniversariante` VARCHAR(50) NOT NULL,
  `dt_nascimento_aniversariante` DATE NOT NULL,
  `nm_responsavel` VARCHAR(50) NOT NULL,
  `id_buffet` INT NOT NULL,
  PRIMARY KEY (`cd_festa`),
  INDEX `fk_tb_festa_tb_buffet1_idx` (`id_buffet` ASC) VISIBLE,
  CONSTRAINT `fk_tb_festa_tb_buffet1`
    FOREIGN KEY (`id_buffet`)
    REFERENCES `db_buffet`.`tb_buffet` (`cd_buffet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_buffet`.`tb_fornecedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_buffet`.`tb_fornecedor` ;

CREATE TABLE IF NOT EXISTS `db_buffet`.`tb_fornecedor` (
  `cd_fornecedor` INT NOT NULL AUTO_INCREMENT,
  `nm_fornecedor` VARCHAR(100) NOT NULL,
  `nm_email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`cd_fornecedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_buffet`.`tb_mesa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_buffet`.`tb_mesa` ;

CREATE TABLE IF NOT EXISTS `db_buffet`.`tb_mesa` (
  `cd_mesa` INT NOT NULL AUTO_INCREMENT,
  `nr_mesa` INT(3) NOT NULL,
  `id_buffet` INT NOT NULL,
  `id_qrcode` INT NOT NULL,
  PRIMARY KEY (`cd_mesa`),
  INDEX `fk_tb_mesa_tb_buffet_idx` (`id_buffet` ASC) VISIBLE,
  INDEX `fk_tb_mesa_tb_qrcode1_idx` (`id_qrcode` ASC) VISIBLE,
  CONSTRAINT `fk_tb_mesa_tb_buffet`
    FOREIGN KEY (`id_buffet`)
    REFERENCES `db_buffet`.`tb_buffet` (`cd_buffet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_mesa_tb_qrcode1`
    FOREIGN KEY (`id_qrcode`)
    REFERENCES `db_buffet`.`tb_qrcode` (`cd_qrcode`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_buffet`.`tb_pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_buffet`.`tb_pedido` ;

CREATE TABLE IF NOT EXISTS `db_buffet`.`tb_pedido` (
  `cd_pedido` INT NOT NULL AUTO_INCREMENT,
  `id_festa` INT NOT NULL,
  `id_mesa` INT NOT NULL,
  `hr_pedido` DATETIME NOT NULL DEFAULT current_timestamp,
  `st_pedido` CHAR(1) NOT NULL,
  PRIMARY KEY (`cd_pedido`),
  INDEX `fk_tb_pedido_tb_mesa1_idx` (`id_mesa` ASC) VISIBLE,
  INDEX `fk_tb_pedido_tb_festa1_idx` (`id_festa` ASC) VISIBLE,
  CONSTRAINT `fk_tb_pedido_tb_mesa1`
    FOREIGN KEY (`id_mesa`)
    REFERENCES `db_buffet`.`tb_mesa` (`cd_mesa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_pedido_tb_festa1`
    FOREIGN KEY (`id_festa`)
    REFERENCES `db_buffet`.`tb_festa` (`cd_festa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_buffet`.`tb_pedido_produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_buffet`.`tb_pedido_produto` ;

CREATE TABLE IF NOT EXISTS `db_buffet`.`tb_pedido_produto` (
  `id_pedido` INT NOT NULL,
  `id_produto` INT NOT NULL,
  PRIMARY KEY (`id_pedido`, `id_produto`),
  INDEX `fk_tb_pedido_has_tb_produto_tb_produto1_idx` (`id_produto` ASC) VISIBLE,
  INDEX `fk_tb_pedido_has_tb_produto_tb_pedido1_idx` (`id_pedido` ASC) VISIBLE,
  CONSTRAINT `fk_tb_pedido_has_tb_produto_tb_pedido1`
    FOREIGN KEY (`id_pedido`)
    REFERENCES `db_buffet`.`tb_pedido` (`cd_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_pedido_has_tb_produto_tb_produto1`
    FOREIGN KEY (`id_produto`)
    REFERENCES `db_buffet`.`tb_produto` (`cd_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_buffet`.`tb_produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_buffet`.`tb_produto` ;

CREATE TABLE IF NOT EXISTS `db_buffet`.`tb_produto` (
  `cd_produto` INT NOT NULL AUTO_INCREMENT,
  `nm_produto` VARCHAR(50) NOT NULL,
  `qt_estoque` INT(10) NOT NULL,
  `qt_minima_estoque` INT(10) NOT NULL,
  `id_categoria` INT NOT NULL,
  `id_buffet` INT NOT NULL,
  PRIMARY KEY (`cd_produto`),
  INDEX `fk_tb_produto_tb_categoria1_idx` (`id_categoria` ASC) VISIBLE,
  INDEX `fk_tb_produto_tb_buffet1_idx` (`id_buffet` ASC) VISIBLE,
  CONSTRAINT `fk_tb_produto_tb_categoria1`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `db_buffet`.`tb_categoria` (`cd_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_produto_tb_buffet1`
    FOREIGN KEY (`id_buffet`)
    REFERENCES `db_buffet`.`tb_buffet` (`cd_buffet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_buffet`.`tb_qrcode`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_buffet`.`tb_qrcode` ;

CREATE TABLE IF NOT EXISTS `db_buffet`.`tb_qrcode` (
  `cd_qrcode` INT NOT NULL AUTO_INCREMENT,
  `nm_caminho` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`cd_qrcode`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

select * from tb_buffet;
